name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # -
      #   name: Shorten commit id
      #   shell: bash
      #   run: |
      #     echo "COMMIT_ID=${github.sha::6}" >> "GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mehradman/python-app:${{ github.sha }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      -
        name: Cloning the repo
        uses: actions/checkout@v3
      -
        name: Modify values file
        shell: bash
        run: |
          sudo apt update
          sudo apt install yq -y
          yq -Yi '.image.tag = "${{github.sha}}"' charts/python-app/values.yaml
      - 
        name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update values.yaml with commit ${{github.sha}}'
      -
        name: Install Argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      -
        name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app